name: login_page
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  another_flushbar: ^1.12.30
  build_runner: ^2.4.15
  connectivity_plus: ^6.1.3
  crypto: ^3.0.6
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  email_validator: ^3.0.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^4.2.1
  http: ^1.3.0
  intl: ^0.19.0
  meta: ^1.15.0
  mockito: ^5.4.5
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  ideo_core:
       git:
         url: https://github.com/jenistonantony/Login-Page_Assesment-1 
    
  

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/images/
 
